name: Build and Deploy Python App

on:
  push:
    branches:
      - main

env:
  AZURE_FUNCTIONAPP_NAME: mynewparserapp-v2
  PYTHON_VERSION: 3.11

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: '.'
          enable-oryx-build: true
